# Generated by Django 6.0.3 on 2026-03-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='DogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус собаки',
                'verbose_name_plural': 'Статусы собак',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип снаряжения',
                'verbose_name_plural': 'Типы снаряжения',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('report_type', models.CharField(max_length=100, verbose_name='Тип отчёта')),
                ('template_file', models.FileField(upload_to='reports/templates/', verbose_name='Файл шаблона')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон отчёта',
                'verbose_name_plural': 'Шаблоны отчётов',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Кинолог', 'Кинолог'), ('Ветеринар', 'Ветеринар'), ('Руководитель', 'Руководитель')], max_length=50, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='TrainingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Навык тренировки',
                'verbose_name_plural': 'Навыки тренировок',
            },
        ),
        migrations.CreateModel(
            name='VeterinaryProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Тип ветеринарной процедуры',
                'verbose_name_plural': 'Типы ветеринарных процедур',
            },
        ),
        migrations.CreateModel(
            name='DogSpecializationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(verbose_name='Дата получения специализации')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dogspecialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация собаки',
                'verbose_name_plural': 'Специализации собак',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('rank', models.CharField(max_length=100, verbose_name='Звание')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Подразделение')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фотография')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Дата аттестации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учётная запись')),
                ('roles', models.ManyToManyField(blank=True, to='dogs.role', verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('gender', models.CharField(choices=[('Кобель', 'Кобель'), ('Сука', 'Сука')], max_length=10, verbose_name='Пол')),
                ('color_marks', models.TextField(blank=True, verbose_name='Окрас и приметы')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dogs/photos/', verbose_name='Фотография')),
                ('origin_story', models.TextField(blank=True, verbose_name='История происхождения')),
                ('main_kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dogs', to='dogs.employee', verbose_name='Основной кинолог')),
                ('specializations', models.ManyToManyField(blank=True, through='dogs.DogSpecializationLink', to='dogs.dogspecialization', verbose_name='Специализации')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.dogstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Служебная собака',
                'verbose_name_plural': 'Служебные собаки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('current_condition', models.CharField(max_length=200, verbose_name='Текущее состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.equipmenttype', verbose_name='Тип снаряжения')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='dogs.servicedog', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Снаряжение',
                'verbose_name_plural': 'Снаряжение',
            },
        ),
        migrations.AddField(
            model_name='dogspecializationlink',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.servicedog', verbose_name='Собака'),
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=300, verbose_name='Место проведения')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('results', models.TextField(blank=True, verbose_name='Результаты')),
                ('documents', models.FileField(blank=True, null=True, upload_to='events/documents/', verbose_name='Документы')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dogs.servicedog', verbose_name='Собака')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.eventtype', verbose_name='Тип мероприятия')),
                ('kennel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dogs.employee', verbose_name='Кинолог')),
            ],
            options={
                'verbose_name': 'Служебное мероприятие',
                'verbose_name_plural': 'Служебные мероприятия',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('weather_conditions', models.CharField(blank=True, max_length=200, verbose_name='Погодные условия')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='dogs.servicedog', verbose_name='Собака')),
                ('kennel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='dogs.employee', verbose_name='Кинолог')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.trainingskill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField(verbose_name='Дата процедуры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('next_procedure_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей процедуры')),
                ('is_routine', models.BooleanField(default=True, verbose_name='Плановая процедура')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_records', to='dogs.servicedog', verbose_name='Собака')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.veterinaryproceduretype', verbose_name='Тип процедуры')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_records', to='dogs.employee', verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Ветеринарная запись',
                'verbose_name_plural': 'Ветеринарные записи',
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dogspecializationlink',
            unique_together={('dog', 'specialization')},
        ),
    ]
